# Generated by Django 3.0.3 on 2020-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200530_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Karabük', 'Karabük'), ('Edirne', 'Edirne'), ('Aydın', 'Aydın'), ('Antalya', 'Antalya'), ('Kocaeli', 'Kocaeli'), ('Muğla', 'Muğla')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.IntegerField(blank=True, choices=[('1', '1+0'), ('2', '1+1'), ('2', '2+0'), ('3', '2+1'), ('4', '3+1'), ('5', '4+1'), ('6', '4+2'), ('7', '5+2')]),
        ),
    ]
