# Generated by Django 3.0.3 on 2020-05-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200530_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room_number',
            field=models.CharField(blank=True, choices=[('1+0', '1+0'), ('1+1', '1+1'), ('2+0', '2+0'), ('2+1', '2+1'), ('3+1', '3+1'), ('4+1', '4+1'), ('4+2', '4+2'), ('5+2', '5+2')], max_length=255),
        ),
    ]
